In [3]:
# !nvidia-smi

In [17]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.4.1
True


In [18]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
print(torch.cuda.device_count()) # Count number of devices

cuda
1


https://www.learnpytorch.io/00_pytorch_fundamentals/

# Introduction to Tensors

### Creating tensors
https://pytorch.org/docs/stable/tensors.html

In [6]:
# creates a tensor out of a scalar or array or list
sc = torch.tensor(7)
sc

tensor(7)

In [7]:
sc.dtype #default 

torch.int64

In [8]:
sc.ndim # number of dimensions

0

In [9]:
torch.tensor([(2,3,4),(1,2,3)])

tensor([[2, 3, 4],
        [1, 2, 3]])

In [10]:
# fails because output of item() shud be scalar
torch.tensor([(2,3,4),(1,2,3)]).item()

RuntimeError: a Tensor with 6 elements cannot be converted to Scalar

In [11]:
sc.item() # gets tensor as python scalar int/float as found

7

In [12]:
# Random tensors. Any of below 3 methods work

# rand_ts = torch.rand((2,3,4))
# rand_ts = torch.rand(2,3,4)
rand_ts = torch.rand(size=(2,3,4))

In [13]:
rand_ts

tensor([[[0.5698, 0.8356, 0.5811, 0.4444],
         [0.2036, 0.5727, 0.6941, 0.6974],
         [0.8052, 0.4016, 0.8065, 0.1479]],

        [[0.9198, 0.7113, 0.8565, 0.9473],
         [0.5552, 0.7393, 0.4922, 0.4293],
         [0.1189, 0.6211, 0.3460, 0.1847]]])

#### Default type for random tensor is float32

In [14]:
rand_ts.dtype

torch.float32

In [15]:
rand_ts.ndim # 4 columns, 3 rows, and 2 such combinations, thats y ndim = 3

3

In [16]:
# Zeros
zero_ts = torch.zeros(1,3,1)
zero_ts

tensor([[[0.],
         [0.],
         [0.]]])

In [17]:
# Ones
ones_ts = torch.ones(3,4)
ones_ts

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
rand_ts.shape

torch.Size([2, 3, 4])

In [19]:
zero_ts.shape

torch.Size([1, 3, 1])

In [20]:
zero_ts*rand_ts

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Ranges and Tensor-like

Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [21]:
range_ts = torch.arange(0,10,2)

In [22]:
range_ts

tensor([0, 2, 4, 6, 8])

In [23]:
zero_like_ts = torch.zeros_like(input=range_ts)

In [24]:
zero_like_ts

tensor([0, 0, 0, 0, 0])

## Data Dtypes

Most common attributes you'll want to find out about tensors are:

- shape - what shape is the tensor? (some operations require specific shape rules)
- dtype - what datatype are the elements within the tensor stored in?
- device - what device is the tensor stored on? (usually GPU or CPU)

Tips:
- PyTorch likes calculations between tensors to be on the same device
- PyTorch likes calculations between tensors to be of the same dtype

In [25]:
# default params
print(rand_ts.dtype)
print(rand_ts.shape)
print(rand_ts.device)

torch.float32
torch.Size([2, 3, 4])
cpu


In [26]:
rand_ts_custom = torch.rand((2,3,4), device="cuda",dtype=torch.float16, requires_grad=False)
# rand_ts_custom = rand_ts.type(torch.half) # to change the type

In [27]:
print(rand_ts_custom.type())
print(rand_ts_custom.dtype)
print(rand_ts_custom.requires_grad)
print(rand_ts_custom.device)

torch.cuda.HalfTensor
torch.float16
False
cuda:0


## Manipulation

In [3]:
ts = torch.tensor([1,2,3,4])

In [30]:
ts + 10 # or the torch.add(ts,10)

tensor([11, 12, 13, 14])

In [31]:
ts*10 # or the torch.multiply(ts,10)

tensor([10, 20, 30, 40])

In [32]:
ts-10 # or the torch.subtract(ts,10)

tensor([-9, -8, -7, -6])

In [34]:
ts/10 # or the torch.divide(ts,10)

tensor([0, 0, 0, 0])

In [37]:
ts//10 #torch.floor_divide(ts,10)


tensor([0, 0, 0, 0])

### Matrix multiplication

a x b Matrix with c x d matrix

- The inner dimensions must match i.e. b=c
- The final dimension is the shape of the outer dimensions i.e. a x d matrix

In [38]:
ts1 = torch.rand(2,3)
ts2 = torch.rand(2,3)

In [39]:
ts1 @ ts2 # torch.matmul(ts1,ts2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [40]:
ts1 = torch.rand(2,3)
ts2 = torch.rand(3,2)

In [41]:
ts1@ts2

tensor([[0.4803, 0.6850],
        [0.6470, 0.4910]])

### MIn, max, avg

In [11]:
ts

tensor([1, 2, 3, 4])

In [14]:
ts.argmin(), ts[ts.argmin()]

(tensor(0), tensor(1))

In [15]:
ts.argmax(), ts[ts.argmax()]

(tensor(3), tensor(4))

In [16]:
torch.rand(2,3,4)

tensor([[[0.5059, 0.5285, 0.4860, 0.1942],
         [0.0107, 0.4080, 0.7007, 0.3680],
         [0.4597, 0.3635, 0.3101, 0.0916]],

        [[0.7486, 0.3754, 0.3212, 0.1086],
         [0.4810, 0.8235, 0.7826, 0.8184],
         [0.6338, 0.0046, 0.2581, 0.2643]]])

### Viewing, Reshaping, restacking, squeezing and unsqueezing

Since these all return views, changing the variable that has the view will change the content of the original tensor as well

In [19]:
ts = torch.rand(3,4)

In [20]:
ts

tensor([[0.7964, 0.7321, 0.0875, 0.7209],
        [0.8276, 0.4540, 0.7142, 0.9574],
        [0.4914, 0.2351, 0.4400, 0.4288]])

In [22]:
ts2 = ts.view(2,6)

In [23]:
ts2

tensor([[0.7964, 0.7321, 0.0875, 0.7209, 0.8276, 0.4540],
        [0.7142, 0.9574, 0.4914, 0.2351, 0.4400, 0.4288]])

In [26]:
print(ts2[1][3])
ts2[1][3] = 0.544

tensor(0.2351)


In [27]:
ts2

tensor([[0.7964, 0.7321, 0.0875, 0.7209, 0.8276, 0.4540],
        [0.7142, 0.9574, 0.4914, 0.5440, 0.4400, 0.4288]])

In [29]:
ts # corresponding element changed to 0.5440

tensor([[0.7964, 0.7321, 0.0875, 0.7209],
        [0.8276, 0.4540, 0.7142, 0.9574],
        [0.4914, 0.5440, 0.4400, 0.4288]])

In [50]:
#unsqueeze
ts = torch.rand(2,3,3)
print(ts.size())
print(ts)

torch.Size([2, 3, 3])
tensor([[[0.9936, 0.6973, 0.5342],
         [0.5955, 0.0391, 0.1610],
         [0.5737, 0.8437, 0.0135]],

        [[0.1396, 0.6287, 0.1836],
         [0.2877, 0.8225, 0.8471],
         [0.6070, 0.6017, 0.2196]]])


In [47]:
ts.ndim

3

#### unsqueeze can be done from [ts.ndim - 1 to ts.ndim]

E.g. if ts.ndim = 3 then

-4 corresponds to 0

-3 -> 1

-2 -> 2

-1 -> 3

In [58]:
ts = torch.rand(2,3,3)
ts = ts.unsqueeze(dim=-3)
print(ts.size())
ts

torch.Size([2, 1, 3, 3])


tensor([[[[0.2223, 0.5492, 0.3033],
          [0.0053, 0.8916, 0.6272],
          [0.2188, 0.8294, 0.3842]]],


        [[[0.7616, 0.6608, 0.7325],
          [0.2956, 0.9009, 0.7750],
          [0.1259, 0.9355, 0.5821]]]])

### Indexing

In [102]:
ts = torch.randint(100, (2,3,4))
ts

tensor([[[26, 80, 85, 89],
         [55, 66, 13,  4],
         [17, 13, 25,  2]],

        [[47,  3, 99, 57],
         [73, 68, 46,  3],
         [82, 21, 83, 92]]])

In [103]:
ts[0][0][0], ts[0,0,0]

(tensor(26), tensor(26))

In [124]:
ts[:,2:], ts[:,2], ts[:,2,3:], ts[:,2,3]

(tensor([[[17, 13, 25,  2]],
 
         [[82, 21, 83, 92]]]),
 tensor([[17, 13, 25,  2],
         [82, 21, 83, 92]]),
 tensor([[ 2],
         [92]]),
 tensor([ 2, 92]))

In [101]:
a = torch.rand(3,2,2)
print(a)
a[:,:1,:]

tensor([[[0.6502, 0.8175],
         [0.6612, 0.7362]],

        [[0.0326, 0.3986],
         [0.1473, 0.3721]],

        [[0.2861, 0.9465],
         [0.0468, 0.4048]]])


tensor([[[0.6502, 0.8175]],

        [[0.0326, 0.3986]],

        [[0.2861, 0.9465]]])

### Numpy and Tensor 

In [128]:
ts.numpy()

array([[[26, 80, 85, 89],
        [55, 66, 13,  4],
        [17, 13, 25,  2]],

       [[47,  3, 99, 57],
        [73, 68, 46,  3],
        [82, 21, 83, 92]]], dtype=int64)

In [130]:
import numpy as np
arr = np.arange(0,10,2)
t_arr = torch.from_numpy(arr)
t_arr

tensor([0, 2, 4, 6, 8], dtype=torch.int32)